/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.uia.is12.view;

import com.uia.is12.business.QATrackerBusiness;
import com.uia.is12.domain.Usuario;
import com.uia.is12.data.UsuarioDAO;
import com.uia.is12.panel.QAGradient;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author raiam.quesada.urena
 */
public class QATrackerRegister extends javax.swing.JFrame {
    private QATrackerBusiness dao = new QATrackerBusiness();
    
    /**
     * Creates new form QATrackerMainMenu
     */
    public QATrackerRegister() {
        initComponents();
        addPanel();
        
    }
    
    public final void addPanel(){
        QAGradient as = new QAGradient("MAIN");
        this.setLayout(new BorderLayout());
        this.add(as, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollbar1 = new java.awt.Scrollbar();
        jTextField2 = new javax.swing.JTextField();
        nombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        pass2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        state = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        username = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        nombre1 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        nombre3 = new javax.swing.JLabel();
        puesto = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 200, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(scrollbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nombre.setText("Puesto");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Ingrese los datos requeridos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 11, 400, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, 450, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 95, -1, 20));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 200, -1));
        getContentPane().add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 200, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Repetir Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uia/is12/images/volver.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 80, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uia/is12/images/registrar.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 80, 30));

        state.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        state.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 340, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 600, -1));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 200, -1));
        getContentPane().add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 200, -1));
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 60, -1));

        nombre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nombre1.setText("Nombre de Usuario:");
        getContentPane().add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 65, -1, 20));

        nombre2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nombre2.setText("Nombre y apellido:");
        getContentPane().add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 30));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 200, -1));

        nombre3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nombre3.setText("Edad");
        getContentPane().add(nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, 30));

        puesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Desarrollador", "QA", "Supervisor" }));
        getContentPane().add(puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setIcon(updateImageButton("../images/registrarHover.png"));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setIcon(updateImageButton("../images/registrar.png"));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setIcon(updateImageButton("../images/volverHover.png"));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setIcon(updateImageButton("../images/volver.png"));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new QATrackerView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String usernameLabel = name.getText();
        Usuario user = new Usuario();
        if(!password.getText().equals("") && password.getText().equals(pass2.getText()) && !username.getText().equals("") && !name.getText().equals("") && !lastname.getText().equals("") && !age.getText().equals("") ){
           try {
               user.setUsername(username.getText());
               user.setPassword(password.getText());
               user.setName(name.getText());
               user.setLastname(lastname.getText());
               user.setEdad(Integer.parseInt(age.getText()));
               user.setRole((String) puesto.getSelectedItem());
               boolean res = dao.insertarDatos(user);
               if(res == true){
                    state.setText("Nombre de usuario ya existe. Por favor ingrese uno nuevo.");
               }else
                    state.setText("Usuario ingresado correctamente.");
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
            } 
        }else {
            state.setText("Revise las contraseñas o llene todos los campos");
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public ImageIcon updateImageButton(String path){
        InputStream imgStream = QATrackerView.class.getResourceAsStream(path);
        ImageIcon newImage = new ImageIcon();
        try {
            BufferedImage myImg = ImageIO.read(imgStream);
            newImage = new ImageIcon(myImg);
        } catch (IOException ex) {
            Logger.getLogger(QATrackerView.class.getName()).log(Level.SEVERE, null, ex);
        }  
        return newImage;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QATrackerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QATrackerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QATrackerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QATrackerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QATrackerRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JLabel nombre3;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JPasswordField password;
    private javax.swing.JComboBox puesto;
    private java.awt.Scrollbar scrollbar1;
    private javax.swing.JLabel state;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
